version: '2'
services:

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    links:
      - mongo
      - rocketchat
      - jenkins
    restart: always

  mongo:
    container_name: mongo
    image: mongo:3.2
    volumes:
      - ./rocket.chat/data/db:/data/db
      - ./rocket.chat/data/dump:/dump
    command: mongod --smallfiles
    restart: always

  rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:latest
    volumes:
      - ./rocket.chat/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.pojo.pl:80
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    depends_on:
      - mongo    
    restart: always

  jenkins:
    container_name: jenkins
    image: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:z
    restart: always
