version: '2'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    restart: always
    command: mongod --smallfiles

  rocketchat:
    image: rocketchat/rocket.chat:latest
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.pojo.pl:80
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    depends_on:
      - mongo
    ports:
      - 80:3000
    restart: always
